#!/usr/bin/env bash
# vim:ft=bash
# Author: Astatoru (https://github.com/Astatoru)
# Description: A simple script that backs up your Remnawave's database and config and uploads it to Github repository
# Dependencies: docker: Database backup
#               tar: Compression to .tar.gz
#               gzip: Compression to .tar.gz
#
# This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Ugly date
DATE=$(date +%Y_%m_%d_%H_%M_%S%Z)
# Pretty date
DATE2=$(date +%Y-%m-%d@%H:%M:%S%Z)
# Script dependencies
declare -a DEPENDENCIES="(docker tar gzip)"
# Toggle root support
declare ROOT="${ROOT:-OFF}"

# Toggle database backup
declare BACKUPDB="${BACKUPDB:-OFF}"
# Database username
declare DBUSER="${DBUSER:-postgres}"
# Path where database will be dumped
declare DUMPPATH="${DUMPPATH:-$PWD}"
# Dump name
declare DUMPNAME="${DUMPNAME:-database-$DATE.dump}"
# Path to archive
declare ARCHIVEPATH="${ARCHIVEPATH:-$PWD}"
# Name of archive
declare ARCHIVENAME="${ARCHIVENAME:-database-$DATE.tar.gz}"
# Databse container name
declare CONTAINER="remnawave-db"

# Toggle panel config backup
declare BACKUPCONFIG="${BACKUPCONFIG:-OFF}"
# Path where to look for panel config
declare CONFIGPATH="${CONFIGPATH:-/opt/remnawave}"
# Path to archive with config backup
declare ARCHIVEPATH2="${ARCHIVEPATH2:-$PWD}"
# Archive name with config
declare ARCHIVENAME2="${ARCHIVENAME2:-config-$DATE.tar.gz}"

# Toggle github support
declare GITHUB="${GITHUB:-OFF}"
# Path to github repository
declare REPOSITORY

# Display error messages
error() {
  local MESSAGE="$1"
  # Check whether stderr is in interactive mode
  if [[ -t 2 ]]; then
    >&2 printf "%b\n" "\033[01;31mERROR\033[0m: $MESSAGE"
  else
    >&2 printf "%s\n" "ERROR: $MESSAGE"
  fi
}

# Display info messages
info() {
  local MESSAGE="$1"
  # Check whether stdout is in interactive mode
  if [[ -t 1 ]]; then
    printf "%b\n" "\033[01;34mINFO\033[0m: $MESSAGE"
  else
    printf "%s\n" "INFO: $MESSAGE"
  fi
}

# Display help message
help() {
  cat <<EOF
Usage:
  ${0##*/} [OPTION]

Options:
  --help                Show this help message
  --root                Allow running the script as root or sudo (not recommended)
  --all                 Alternative for using the --backupdb --backupconfig --github options simultaneously
  --backupdb            Backup Remnawave's database
  --dbuser              Database user (Default: postgres)
  --dumppath            Path to where to dump database (Default: current directory)
  --dumpname            Database dump file's path (Default: current directory)
  --dumparchpath        Path where to create .tar.gz archive with database dump (Default: current directory)
  --dumparchname        Name of the archive with database dump (Default: $ARCHIVENAME)
  --container           Name of the docker container responsible for Remnawave's database (Default: remnawave-db)
  --backupconfig        Backup Remnawave's config
  --configpath          Path to config (Default: /opt/remnawave)
  --configarchpath      Path where to create .tar.gz archive with config (Default: current directory)
  --configarchname      Name of the archive with config backup (Default: $ARCHIVENAME2)
  --github              Upload archive(s) with backup to Github repository
  --repository          Path to your repository (Default: empty)
EOF
  trap "" EXIT
  exit 0
}

# Display help if no options or arguments were provided
checkOpts() {
  if (($# == 0)); then
    help
  fi
}

# Parse script options
parseOpts() {
  local ARGS
  ARGS=$(getopt --longoptions "help,root,all,backupdb,dbuser:,dumppath:,dumpname:,dumparchpath:,dumparchname:,container:,backupconfig,configpath:,configarchpath:,configarchname:,github,repository:" --options "" --name $'\033[01;31mERROR\033[0m' -- "$@") || exit 1
  eval set -- "$ARGS"

  for ARG in "$@"; do
    case "$ARG" in
    --help)
      help
      ;;
    --root)
      ROOT="ON"
      shift
      ;;
    --all)
      BACKUPDB="ON"
      BACKUPCONFIG="ON"
      GITHUB="ON"
      shift
      ;;
    --backupdb)
      BACKUPDB="ON"
      shift
      ;;
    --dbuser)
      DBUSER="$2"
      shift 2
      ;;
    --dumppath)
      DUMPPATH="$2"
      shift 2
      ;;
    --dumpname)
      DUMPNAME="$2"
      shift 2
      ;;
    --dumparchpath)
      ARCHIVEPATH="$2"
      shift 2
      ;;
    --dumparchname)
      ARCHIVENAME="$2"
      shift 2
      ;;
    --container)
      CONTAINER="$2"
      shift 2
      ;;
    --backupconfig)
      BACKUPCONFIG="ON"
      shift
      ;;
    --configpath)
      CONFIGPATH="$2"
      shift 2
      ;;
    --configarchpath)
      ARCHIVEPATH2="$2"
      shift 2
      ;;
    --configarchname)
      ARCHIVENAME2="$2"
      shift 2
      ;;
    --github)
      GITHUB="ON"
      shift
      ;;
    --repository)
      REPOSITORY="$2"
      shift 2
      ;;
    --)
      shift
      ;;
    esac
  done
}

# Check whether the script is run as root
checkRoot() {
  # If "--root" option is used
  # Skip the check
  if [[ "$ROOT" = "OFF" ]]; then
    if ((EUID == 0)); then
      error "Running the script as root is discouraged, but you can disable this check using \"--root\" option"
      exit 1
    fi
  fi
}

# Check whether dependencies are installed
checkDependencies() {
  for CMD in "${DEPENDENCIES[@]}"; do
    if ! command -v "$CMD" &>/dev/null; then
      error "$CMD is not installed"
      exit 1
    # If docker cannot run as root
    # Exit the script
    elif [[ "$CMD" = "docker" ]]; then
      if ! docker ps &>/dev/null; then
        error "Your current user cannot run docker without root priveleges"
        exit 1
      fi
    fi
  done
}

# Remove temporary files
removeTemporary() {
  rm -f "$DUMPPATH/$DUMPNAME"
  rm -f "$ARCHIVEPATH/$ARCHIVENAME"
  rm -f "$ARCHIVEPATH2/$ARCHIVENAME2"
}

# Backup database
backupDatabase() {
  # Check whether container with database is up
  local CONTAINERUP
  CONTAINERUP=$(2>/dev/null docker inspect --format "{{.Name}}" "$CONTAINER" || true)
  if [[ "$BACKUPDB" = "ON" ]]; then
    # Check whether path to database dump is writeable
    # And is a directory
    if [[ ! -w "$DUMPPATH" && ! -d "$DUMPPATH" ]]; then
      error "$DUMPPATH is either not writable or not a directory"
      exit 1
    # Check whether path to archive is writeable
    # And is a directory
    elif [[ ! -w "$ARCHIVEPATH" && ! -d "$ARCHIVEPATH" ]]; then
      error "$ARCHIVEPATH is either not writable or not a directory"
      exit 1
    # Check whether container with database is up
    elif [[ ! "${CONTAINERUP#*/}" = "$CONTAINER" ]]; then
      error "Container \"$CONTAINER\" doesn't exists"
      exit 1
    fi
    # Dump database
    docker exec --tty "$CONTAINER" pg_dumpall --clean --username="$DBUSER" >"$DUMPPATH/$DUMPNAME"
    # Compress dump to .tar.gz archive
    tar --create --gzip --file="$ARCHIVEPATH/$ARCHIVENAME" --directory "$DUMPPATH" "$DUMPNAME"
    # Remove dump
    rm -f "$DUMPPATH/$DUMPNAME"
    info "Archive: \"$ARCHIVENAME\" created successfully"
  fi
}

# Backup config
backupConfig() {
  if [[ "$BACKUPCONFIG" = "ON" ]]; then
    # Check whether config path exists and is a directory
    if [[ ! -d "$CONFIGPATH" && ! -e "$CONFIGPATH" ]]; then
      error "$CONFIGPATH is either doesn't exist or not a directory"
      exit 1
    # Check whether path to archive is writeable
    # And is a directory
    elif [[ ! -w "$ARCHIVEPATH2" && ! -d "$ARCHIVEPATH2" ]]; then
      error "$ARCHIVEPATH2 is either doesn't exist or not a directory"
      exit 1
    fi
    # Create archive with config backup
    tar --create --gzip --file="$ARCHIVEPATH2/$ARCHIVENAME2" "$CONFIGPATH" 2>/dev/null
    info "Archive: \"$ARCHIVENAME2\" created successfully"
  fi
}

# Upload archives to Github repository
uploadToGithub() {
  # Check whether user selected anything for backup
  if [[ "$BACKUPDB" = "ON" || "$BACKUPCONFIG" = "ON" ]]; then
    if [[ "$GITHUB" = "ON" ]]; then
      # Check whether repository is writeable
      # And is a directory
      if [[ ! -w "$REPOSITORY" && ! -d "$REPOSITORY" ]]; then
        error "$REPOSITORY is either not writable or not a directory"
        exit 1
      fi
      # Push changes to github
      # If database backup is enabled
      # Move archive with database to repository
      if [[ "$BACKUPDB" = "ON" ]]; then
        mv "$ARCHIVENAME" "$REPOSITORY"
      fi
      # If config backup is enabled
      # Move archive with config to repository
      if [[ "$BACKUPCONFIG" = "ON" ]]; then
        mv "$ARCHIVENAME2" "$REPOSITORY"
      fi
      # Remove temporary files
      removeTemporary
      # Go to repository
      cd "$REPOSITORY"
      # Pull changes from remote repository before staging
      git pull
      # Stage, create commit and push changes to remote repository
      git add .
      git commit --message "$HOSTNAME backup: $DATE2"
      git push
      info "Backup uploaded to github"
    fi
  fi
}

# Message at the end of the script
endMessage() {
  if [[ "$BACKUPDB" = "ON" || "$BACKUPCONFIG" = "ON" ]]; then
    info "Remnawave backup successfully made at $DATE2"
  else
    info "Seems like you haven't selected anything for backup"
  fi
}

# Main function
main() {
  checkOpts "$@"
  parseOpts "$@"
  checkRoot
  checkDependencies
  backupDatabase
  backupConfig
  uploadToGithub
  endMessage
}

# Stop script execution immediately
# If any command below fails
set -o "errexit"
# Throw an error and remove temporary files on exit
trap "error 'Something went wrong. Removing temporary files...'; removeTemporary && exit 1" EXIT

# Execute main function
main "$@"

# Disable trap
trap "" EXIT
